version: '3'

services:
  efood-app:
    container_name: efood-app
    hostname: efood-app
    build:
      context: ./
      dockerfile: dev.dockerfile
    volumes:
      - ./app:/app/app
      - ./prisma:/app/prisma
      - ./public:/app/public
      - ./components:/app/components
      - ./config:/app/config
      - ./actions:/app/actions
      - ./models:/app/models
      - ./lib:/app/lib
      - ./types:/app/types
      - ./hooks:/app/hooks
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - efood
    depends_on:
      postgresdb:
        condition: service_healthy
    stdin_open: true 
    tty: true
  postgresdb:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - PGUSER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=efood
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    networks:
      - efood
    ports:
      - '5432:5432'
    volumes: 
      - ./database/data:/var/lib/postgresql/data

networks:
  efood:
    external: false

# volumes:
#   postgresdb:
#     driver: local